#pragma once
#include <iostream>
#include <math.h>
#include <time.h>
#include "Vector2.h"
#include <stdlib.h> 
#include <string>
#include <windows.h>
#include <mmsystem.h>
#include <conio.h>
#include <fstream>
#include <objidl.h>
#include <gdiplus.h>
#include <chrono>
#include "ConsoleWindow.h"
#include "Activation.h"
#include "Settings.h"
#include "SYDEWindowGame.h"
#include "SYDEGamePlay.h"
#include "SYDETime.h"